# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hooked on TypeScript
email: acbart@udel.edu
description: >- # this means to ignore newlines until "baseurl:"
  Make a frontend website with TypeScript and React Hooks.
baseurl: "/react-hooks-typescript-tome" # the subpath of your site, e.g. /blog
url: "https://greglnelson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  greglnelson
footer_content: "Created by Austin Cory Bart, Josh Lyon, Kurt Hammen, Emma Adelmann, Terry Harvey, Greg Nelson, and Troy Schotter"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/greglelson/react-hooks-typescript-tome" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # The source folder that your files originate from

back_to_top: true
back_to_top_text: "Back to top"

logo: "/images/logo.png"
ga_tracking: G-HLW24YQRMH

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
